### ISSUE TITLE
listAccounts not working?

### ISSUE THREAD

**Issue by Sammy16z** [rhettre/coinbase-advancedtrade-python#1]
I ran the example code -you know the one with the buy_bitcoin method- and I add this to the end of it:

accounts = coinbase_client.listAccounts()
print(accounts)

in return I get:
"{'error': 'NOT_FOUND', 'error_details': "Could not find user's accounts information", 'message': "Could not find user's accounts information"}"

**Comment by thomaslc66** [comment]
What are the permission on you API KEY ?

**Comment by rhettre** [comment]
Fixed in latest commit. CBAuth had body as a string instead of JSON and the 'params=' in coinbase_client was unnecessary. ListAccounts() should work now
