### ISSUE TITLE
Api returning None because of lack of proper authentication

### ISSUE THREAD

**Issue by BuyHigh-SellLow** [rhettre/coinbase-advancedtrade-python#102]
There appears to be an issue with the correct authentication.  Here is a debug error i get when trying to auth, but Im able to get product info fine.  

 DEBUG - https://api.coinbase.com:443 "GET /api/v3/brokerage/products/BTC-USDC?get_tradability_status=False HTTP/11" 200 None

This is the response i get when doing a limit :

response = client.fiat_limit_buy("BTC-USDC", "1", "98219")

could it be the last number is too low for the the btc price?

**Comment by rhettre** [comment]
I haven't run into this
