### ISSUE TITLE
Can't make any sell orders :(

### ISSUE THREAD

**Issue by Warrenx1** [rhettre/coinbase-advancedtrade-python#103]
So I am really new to Python and I want to get into automatic trading. I watched the video on how to use this package, but unfortunately I can't seem to get it to execute sell orders. When I use the "client.fiat_market_buy" orders they do execute, but produce a Nonetype error. However, when I attempt to use any of the market/spot sell orders (client.fiat_limit_sell, etc.), then the terminal just doesn't do anything and it seems like it just hangs. In other instances, I get a 401 error when I attempt to use some chatgpt created debugging script for selling. Any help would be appreciated. 

![Screenshot 2024-11-23 165932](https://github.com/user-attachments/assets/f1da3394-2207-4c02-8ab6-3b5b01be5503)

**Comment by amnjohn** [comment]
@Warrenx1 there is a problem with line 96 in https://github.com/rhettre/coinbase-advancedtrade-python/blob/main/coinbase_advanced_trader/services/order_service.py

If you can manage to pass in the spot price it should work.

**Comment by BuyHigh-SellLow** [comment]
Try decimal.  10.0 instead of 10

```

    def get_spot_price(self, product_id: str) -> Optional[Decimal]:
        """
        Get the spot price for a given product.

        Args:
            product_id (str): The ID of the product.

        Returns:
            Optional[Decimal]: The spot price, or None if an error occurs.
        """
        try:
            response = self.rest_client.get_product(product_id)
            quote_increment = Decimal(response['quote_increment'])

            if 'price' in response:
                price = Decimal(response['price'])
                return price.quantize(quote_increment)

            logger.error(f"'price' field missing in response for {product_id}")
            return None

        except Exception as e:
            logger.error(f"Error fetching spot price for {product_id}: {e}")
            return None
```

**Comment by rhettre** [comment]
I think I fixed it in the latest code here: https://github.com/rhettre/coinbase-advancedtrade-python/pull/106
