### ISSUE TITLE
Explain why we need Python 3.9 to me like im 5 yrs old

### ISSUE THREAD

**Issue by BuyHigh-SellLow** [rhettre/coinbase-advancedtrade-python#104]
Trying to remember, but if this is based on the Coinbase API that is able to use anything newer than 3.6

**Comment by rhettre** [comment]
The official Coinbase wrapper uses a cryptography library. The cryptography library needs to be compiled on a certain version of python or it won't run in AWS. I arbitrarily chose Python 3.9 when I compile the layer. You could choose some other Python version (and I will probably update it sometime in the future) but we'll need to specifically compile for that version of python
