### ISSUE TITLE
Can't add sell or buy orders

### ISSUE THREAD

**Issue by Alrikh** [rhettre/coinbase-advancedtrade-python#105]
how in title:

`import pandas as pd
import time
from coinbase_advanced_trader.enhanced_rest_client import EnhancedRESTClient
from datetime import datetime, timedelta, timezone
import ta
import logging

#the API key have trade enabled

api_key = "***************************"
api_secret = "*****************************"

client = EnhancedRESTClient(api_key=api_key, api_secret=api_secret)

try:
    client.fiat_limit_buy("MATIC-USDC", "1.0", "10.0")
except Exception as error:
    print(error)`
    
    response:
    
![Cattura](https://github.com/user-attachments/assets/2bb2e7fa-b909-4e17-bf4f-b4ec0be65e97)

**Comment by THREELabs** [comment]
I would try to  create new API key

**Comment by Alrikh** [comment]
In file price_service.py, i have rem #if 'price' in response: at 37, and now work
