### ISSUE TITLE
Bug with property mapping

### ISSUE THREAD

**Issue by MatthewLoffredo** [rhettre/coinbase-advancedtrade-python#107]
I had to change this line in order for a normal limit buy to work: 
![image](https://github.com/user-attachments/assets/dac2b2c8-44e7-4045-9389-876a392a298c)

Specifically `id=order_response.success_response['order_id'],`

**Comment by rhettre** [comment]
I belive this was fixed in https://github.com/rhettre/coinbase-advancedtrade-python/pull/106
