### ISSUE TITLE
Does this support derivative trading? 

### ISSUE THREAD

**Issue by Warrenx1** [rhettre/coinbase-advancedtrade-python#108]
I've been trying to get information on the extent of the APIs interaction with derivatives, but I cant seem to come across much and was wondering if anyone knew anything?

**Comment by rhettre** [comment]
I haven't built out any new features. The base SDK supports some limited use cases depending on your jurisdiction. Coinbase Discord is probably best place to get more info. https://discord.com/channels/1220414409550336183/1220417437921443861/1286397385265905754
