### ISSUE TITLE
Strategy question:  Fear / Greed

### ISSUE THREAD

**Issue by BuyHigh-SellLow** [rhettre/coinbase-advancedtrade-python#117]
I was thinking about adding logic on my branch to potentially diversify this since stock fear/greed seems calculated differently.  Wonder what your thoughts are on this?  Do you have any association to the current fear/greed index?

The current one is a crypto fear/greed which is reading greed to some extent.  There many others out there that vary on how it's reported and thus could drastically change the results.  Regardless adding in the consideration for a stock fear/greed (which is currently reading fear) could also be a early precursor or trigger to the changing from greed to fear in the crypto market.  (which is what I think is going to happen)

While the Fear/Greed Index can provide insights into market sentiment, relying solely on it might not be enough. Combining it with other indicators like moving averages, RSI, or MACD can provide a more comprehensive view of market conditions.

**Comment by rhettre** [comment]
I'd be more inclined to include crypto native indicators RSI/MACD/Glassnode integration vs the stock fear and greed index. People can include stock based indicators in their own projects
