### ISSUE TITLE
Latest commits around fear_and_greed 

### ISSUE THREAD

**Issue by BuyHigh-SellLow** [rhettre/coinbase-advancedtrade-python#118]
...seem to have broken the code base.  

https://github.com/rhettre/coinbase-advancedtrade-python/commit/05079de83c1b3f6b70a85b4af0c7e7dcce475a59#diff-17e1b3aa0cc6edac694fda08db7b4bdb2b9ce45b68587af5287966d487d6bc45

```from fear_and_greed import FearAndGreedIndex```

**Comment by BuyHigh-SellLow** [comment]
May i suggest having one main branch with stable tested code, a development branch used for testing releases on a schedule of 2 wk, 2 months, etc and merging in specific tickets based on issues that need fixed.  

Merging straight into main is bad.

**Comment by rhettre** [comment]
What is broken? I've been able to run all the fear and greed functions and limit buys / sells correctly. Did you install the new requirements?

**Comment by BuyHigh-SellLow** [comment]
nm, somehow the auto merge dropped off the added module to requirements.txt
