### ISSUE TITLE
getProductCandles “granularity argument is invalid” error

### ISSUE THREAD

**Issue by zmoney20** [rhettre/coinbase-advancedtrade-python#12]
while using getProductCandles function, I was not able to get a response back due to an error I was seeing via granularity argument being invalid.

I saw someone else was having the same issue: https://forums.coinbasecloud.dev/t/granularity-argument-is-invalid-error/5080

I tested passing in the values into the url as query parameters  and was able to get a response back

```
    return cb_auth(
        Method.GET.value,
        f"/api/v3/brokerage/products/{product_id}/candles?start={start}&end={end}&granularity={granularity}",
    )
```

**Comment by rhettre** [comment]
Merged fix from @zmoney20
