### ISSUE TITLE
Limit order doesnt work, fails on "order_details['success']"

### ISSUE THREAD

**Issue by dudeman2024** [rhettre/coinbase-advancedtrade-python#18]
Running this code:

```
from coinbase_advanced_trader.strategies.limit_order_strategies import fiat_limit_buy
from coinbase_advanced_trader.config import set_api_credentials

# Set your API key and secret
API_KEY = 'foo'
API_SECRET = 'bar'

# Set the API credentials once, and it updates the CBAuth singleton instance
set_api_credentials(API_KEY, API_SECRET)

# Define the trading parameters
product_id = "BTC-USD"  # Replace with your desired trading pair
usd_size = 1  # Replace with your desired USD amount to spend``

# Perform a limit buy
limit_buy_order = fiat_limit_buy(product_id, usd_size)
```

(venv) [me@host coinbase-advancedtrade-python]$ python test_order.py 
Authenticating with Coinbase
Traceback (most recent call last):
  File "/home/me/Code/coinbase-advancedtrade-python/test_order.py", line 16, in <module>
    limit_buy_order = fiat_limit_buy(product_id, usd_size)
  File "/home/me/Code/coinbase-advancedtrade-python/coinbase_advanced_trader/strategies/limit_order_strategies.py", line 66, in fiat_limit_buy
    print (order_details['success'])
KeyError: 'success'

**Comment by rhettre** [comment]
Most of the time when I see that error it's because I don't have the
correct scope on my API keys

**Comment by rhettre** [comment]
Verified that this code works with correct API permissions

**Comment by mrnavdal** [comment]
Hi, I have the same problem. Can you please elaborate on how to set the scope/permissions? I'm fairly new to python and using VS Code. Thanks!
