### ISSUE TITLE
Error while cancelling orders

### ISSUE THREAD

**Issue by gapinvestor** [rhettre/coinbase-advancedtrade-python#25]
I'm getting the error `'proto:\xa0syntax error (line 1:1): unexpected token "{\\"order_ids\\": [{\\"market\\": \\"BTC-USD\\", \\"order_id\\": \\"6659a34f-8ec2-4689-8030-22f02113140d\\"}]}"'` while trying to cancel orders.

This is my function:
```
def cancell_all_pending_orders(self):
        open_orders = coinbase_client.listOrders()
        order_ids = [{'market': order['product_id'], 'order_id': order['order_id']} for order in open_orders]
        order_cancelled = coinbase_client.cancelOrders(order_ids)
        print(f"ORDERS MANAGEMENT | {order_ids} cancelled succesfully")
```

**Comment by rhettre** [comment]
Should be fixed now that we're pointing to the official SDK
