### ISSUE TITLE
Limit Ordering / Options

### ISSUE THREAD

**Issue by THREELabs** [rhettre/coinbase-advancedtrade-python#38]
When doing a limit buy/sell, how do I specify the Limit buy price?

#buy 1 dollar shib at current price
client.fiat_limit_buy("SHIB-USD", "1")

Instead of buying at current price, I want it something like like $0.00001000 (currently $0.00001825)

**Comment by rhettre** [comment]
You can use EnhancedRestClient to reference any of the OOTB Coinbase functions 

Documentation: https://github.com/coinbase/coinbase-advanced-py

I'll update fiat_limit_buy to allow this in a later release

**Comment by THREELabs** [comment]
thanks!

**Comment by rhettre** [comment]
@THREELabs Updated in https://github.com/rhettre/coinbase-advancedtrade-python/pull/39

**Comment by THREELabs** [comment]
awesome thanks for the quick update
