### ISSUE TITLE
Telegram version

### ISSUE THREAD

**Issue by thomaslc66** [rhettre/coinbase-advancedtrade-python#4]
Hey,

Wanted to thank you for your cool work.

I've forked you repo and improved it with some telegram bot command that you can use to set and create order directly with the telegram bot.

Also I've improved the security putting api key in an env file and I created a dockerfile with documentation to build it directly to run.

The telegram bot improvement make the script run continuously and let you send buy order whenever you want and also create DCA order

Have a look and let me know what you think?
https://github.com/thomaslc66/coinbase-advancedtrade-python

Cheers.

Thomas

**Comment by rhettre** [comment]
Really cool! I don't use telegram much, but the idea of interacting with Coinbase backend directly from telegram is great 🔥🔥🔥

I updated some of the code on the initial repo to fix the listAccounts() issue. 

Would be interested in talking about tradeoffs around API keys - using environment variables seems more secure (and best practice) but I'm wondering if I'll be able to teach people on youtube how to use environment variables vs just pasting API keys as plaintext into a file. Would love to hear simple solutions / suggestions if you have any :)

**Comment by thomaslc66** [comment]
Thanks,

Yeah, I would love to help if you need it. 
Maybe to start you can have a look at my config.py file here: https://github.com/thomaslc66/coinbase-advancedtrade-python/blob/main/coinbase_advanced_trader/config.py

You will maybe understand how I load the file and variables which library I use etc.
Then for the docker-compose run, there's a command in the README to send that file as an env file, but you could also pass them one by one in the docker run command --e 'API_KEY'='XXXXX'

But let me know if you want i can show you.
Cheers
