### ISSUE TITLE
AttributeError: 'EnhancedRESTClient' object has no attribute 'get_crypto_balance'

### ISSUE THREAD

**Issue by THREELabs** [rhettre/coinbase-advancedtrade-python#91]
I am noticing the following error regarding 'get_crypto_balance'. I think I tested this earlier on and worked but noticed showing this now. Did something change? 

balance = client.get_crypto_balance("BTC")
AttributeError: 'EnhancedRESTClient' object has no attribute 'get_crypto_balance'

**Comment by rhettre** [comment]
Ran this from a fresh install and it worked correctly. Maybe there are some other issues you have locally - check to make sure your imports are correct, you're instantiating EnhancedRESTClient, and that get_crypto_balance function is available in your enhanced_rest_client.py file:

from coinbase_advanced_trader.enhanced_rest_client import EnhancedRESTClient

api_key = ""
api_secret = ""

client = EnhancedRESTClient(api_key=api_key, api_secret=api_secret)

balance = client.get_crypto_balance("BTC")
print(balance)

**Comment by THREELabs** [comment]
Thank you for checking that out. I'll revisit my code!

**Comment by THREELabs** [comment]
All is good
